name: GTWHouses
version: '${version}'
main: com.edgarssilva.gtwhouses.GTWHouses
author: Edgar Silva
depend:
  - Vault
  - WorldEdit
  - WorldGuard
  - AtumCore

commands:
  house:
    description: Create, delete and manage houses!
    usage: "/house [register|reset|remove|list|rent...]"
    permission: house.houseadmin
    aliases:
      - houses
permissions:
  house.houseplayer:
    description: Allows the player to buy and rent houses.
    default: true
  house.houseadmin:
    description: Allows the player to manage houses.
    default: op