name: GTWHouses
version: '${version}'
main: com.grandtheftwarzone.gtwhouses.server.GTWHouses
author: Edgar Silva
depend:
  - Vault
  - WorldEdit
  - AtumCore

commands:
  house:
    description: Buy, sell, rent and all about houses!
    usage: "/house [register|reset|remove|list|rent...]"
    permission: gtwhouses.houseplayer
    aliases:
      - houses
      - gtwhouse
      - gtwhouses

  shop:
    description: Admin panel to set item prices
    usage: "/shop"
    permission: gtwshops.admin
    aliases:
      - gtwshop
      - gtwshops
      - shops
      - gtwnpcshop

permissions:
 gtwhouses.houseplayer:
    description: Allows the player to buy and rent houses.
    default: true

 gtwhouses.admin:
    description: Allows the player to manage houses.
    default: op

 gtwshops.admin:
    description: Allows the player to manage the shop.
    default: op